### PR TITLE
chore: no redirect for 404

### PR DESCRIPTION
**Pull request by mcdurdin**
The .php extension on the 404 ErrorDocument directive was causing Apache to do a redirect. Removing this means that the original url is maintained.

Also did a little bit of cleanup to the error page at the same time:
* removed (unhelpful) breadcrumbs
* gave a direct link to Keyman Community
* removed IIS-specific code

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by darcywong00** [comment]
hmm, CI failed because aramaic/1.1/aramaic.php refers to aramaic.ico 
even though #625 changed the linke to Aramaic.ico (the actual filename)

**Comment by mcdurdin** [comment]
> The current line has history from 2 years ago, before the change 😕

Yeah because the keyboard deployment keeps on overwriting the file. See https://github.com/keymanapp/keyboards/blob/master/legacy/a/aramaic/source/help/aramaic.php#L103

**Comment by mcdurdin** [comment]
https://github.com/keymanapp/keyboards/pull/2555 should fix the broken ico link

**Pull request merged**
