### PR TITLE
chore: A15S1 staging-branch update

### PR DESCRIPTION
**Pull request by jahorton**
Since we _just_ released v14, a lot of our recent help work was applied to `master`, rather than `staging`.  It's worth noting that some of the 'alpha' versions of our apps (like for iOS) will point to `staging`, so we should probably update `staging` with the new stuff.

### CODE REVIEW

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
This needs to be done with a separate branch for tracking purposes. Closing this PR.

**Comment by jahorton** [comment]
Please tag this PR when you do so.

**Comment by mcdurdin** [comment]
> Or are you saying that simply making a temp branch off of master, thus capturing a 'snapshot' of it, is sufficient?

Yes

**Pull request closed without merging**
