### PR TITLE
chore: 17.0 context documentation updates

### PR DESCRIPTION
**Pull request by Meng-Heng**
Hello!
Some images are not in use for the files here but they are in #1148 PR. Please approve this PR before #1148.

### CODE REVIEW

**Comment by darcywong00** [comment]
I wonder since some of the images are in a 170 folder, maybe can drop the "17.0" in the filename

For example:
170/ui/Debug_Menu17.0.png could be Debug_Menu.png

**Comment by Meng-Heng** [comment]
It uses the 10.0 images when I use Debug_Menu and it does for other images as well. Should I instead use Debug_Menu_1 after the name?

**Comment by darcywong00** [comment]
> Edit: Darcy, I got it working now.

Nice!  I think there's at least 5 more image filenames this applies to

**Comment by Meng-Heng** [comment]
Thank you, Darcy. I got them all renamed now.

**Review by darcywong00 — APPROVED** [review]
lgtm

**Comment by mcdurdin** [comment]
I think this fixes #1089, do you agree?

**Pull request merged**
