### PR TITLE
chore: converts two more pages (no manual edits)

### PR DESCRIPTION
**Pull request by jahorton**

### CODE REVIEW

**Comment by darcywong00** [comment]
See https://github.com/keymanapp/help.keyman.com/pull/744#issuecomment-1625454644 about CI link checker fails.

As the php files get converted to markdown, we should check to see if existing links to the php files also need to be updated.

**Comment by jahorton** [comment]
> See [#744 (comment)](https://github.com/keymanapp/help.keyman.com/pull/744#issuecomment-1625454644) about CI link checker fails.
> 
> As the php files get converted to markdown, we should check to see if existing links to the php files also need to be updated.

That makes sense.  If only the link-checker actually told us what files were linking to them.

In the meantime, I just figured out a little more automation:  when converting a page, the automation tool will now strip file-extensions from internal links.  (`http://` and `https://` in a link will disable the 'stripping' behavior, while relative - and thus, internal - links will be sanitized.)

**Comment by jahorton** [comment]
Also, the latest commit _is_ manual, but that's to patch up the busted links that crept in from recent PRs.

**Review by mcdurdin — APPROVED** [review]
LGTM

**Pull request merged**
