### PR TITLE
docs: convert developer/engine/desktop/14.0/api/IKeymanErrors

### PR DESCRIPTION
**Pull request by Nnyny**
partial fix of: https://github.com/keymanapp/keyman/issues/12347

### CODE REVIEW

**Comment by mcdurdin** [comment]
This has some failing CI -- broken links?

**Comment by Nnyny** [comment]
I checked and the links work. Could it be because of something else?

**Comment by mcdurdin** [comment]
I looked at the error report generated. I think the issue is that `Index.md` should be `index.md` (lower case)!

```
Getting links from: http://localhost:8055/developer/engine/desktop/current-version/api
├─BROKEN─ http://localhost:8055/developer/engine/desktop/14.0/api/IKeymanErrors (HTTP_403)
--
Getting links from: http://localhost:8055/developer/engine/desktop/current-version/api/
├─BROKEN─ http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanErrors (HTTP_403)
--
Getting links from: http://localhost:8055/developer/engine/desktop/14.0/api/
├─BROKEN─ http://localhost:8055/developer/engine/desktop/14.0/api/IKeymanErrors (HTTP_403)
--
Getting links from: http://localhost:8055/developer/engine/desktop/14.0/api/IKeyman
├─BROKEN─ http://localhost:8055/developer/engine/desktop/14.0/api/IKeymanErrors (HTTP_403)
--
Getting links from: http://localhost:8055/developer/engine/desktop/14.0/api/IKeymanCollection
├─BROKEN─ http://localhost:8055/developer/engine/desktop/14.0/api/IKeymanErrors (HTTP_403)
--
Getting links from: http://localhost:8055/developer/engine/desktop/14.0/api/IKeymanObject
├─BROKEN─ http://localhost:8055/developer/engine/desktop/14.0/api/IKeymanErrors (HTTP_403)
--
Getting links from: http://localhost:8055/developer/engine/desktop/current-version/api/IKeyman
├─BROKEN─ http://localhost:8055/developer/engine/desktop/14.0/api/IKeymanErrors (HTTP_403)
--
Getting links from: http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanCollection
├─BROKEN─ http://localhost:8055/developer/engine/desktop/14.0/api/IKeymanErrors (HTTP_[40](https://github.com/keymanapp/help.keyman.com/actions/runs/11321650614/job/31481025916?pr=1622#step:6:41)3)
--
Getting links from: http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanObject
├─BROKEN─ http://localhost:8055/developer/engine/desktop/14.0/api/IKeymanErrors (HTTP_403)
--
Getting links from: http://localhost:8055/developer/engine/desktop/14.0/api/IKeyman/Errors
├─BROKEN─ http://localhost:8055/developer/engine/desktop/14.0/api/IKeymanErrors (HTTP_403)
--
Getting links from: http://localhost:8055/developer/engine/desktop/current-version/api/IKeyman/
├─BROKEN─ http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanErrors (HTTP_403)
--
Getting links from: http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanCollection/
├─BROKEN─ http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanErrors (HTTP_403)
--
Getting links from: http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanObject/
├─BROKEN─ http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanErrors (HTTP_403)
--
Getting links from: http://localhost:80[55](https://github.com/keymanapp/help.keyman.com/actions/runs/11321650614/job/31481025916?pr=1622#step:6:56)/developer/engine/desktop/current-version/api/IKeyman/Errors
├─BROKEN─ http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanErrors (HTTP_403)
--
Getting links from: http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanErrors/Items
├─BROKEN─ http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanErrors/ (HTTP_403)
Getting links from: http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanErrors/Clear
├─BROKEN─ http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanErrors/ (HTTP_403)
--
Getting links from: http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanErrors/Index
├─BROKEN─ http://localhost:8055/developer/engine/desktop/current-version/api/IKeymanErrors/ (HTTP_403)
```

**Review by darcywong00 — APPROVED** [review]
lgtm

**Pull request merged**
