### PR TITLE
auto: Keyman for developer help deployment 📚

### PR DESCRIPTION
**Pull request by mcdurdin**

### CODE REVIEW

**Comment by darcywong00** [comment]
Seed developer/17.0/reference/api

**Comment by mcdurdin** [comment]
@darcywong00 would you mind reviewing this one? we need it merged to get the rest of the links working

**Comment by mcdurdin** [comment]
Don't worry about content -- that will come in the keyman repo in subsequent PRs

**Review by darcywong00 — APPROVED** [review]
rslgtm

**Pull request merged**
