### PR TITLE
chore: Move products/desktop to products/windows

### PR DESCRIPTION
**Pull request by darcywong00**
Fixes point 1 of #285 
>  Rename `products/desktop` folder to `products/windows` and handle forwards. Update site references

Recap of changes:
* Moved products/desktop/ 4.0-13.0 content to products/windows/
* Move products/desktop/version-history to products/windows/version-history
* Move products/desktop/web.config to products/windows/web.config (GitHub didn't quite track this move)
* Update other web.config files to redirect products/desktop to products/windows
* Update menus and homepages to reference Keyman for Windows

Intentionally not tackling Keyman Engine for Desktop atm

TODO
- [x] Delete products/desktop/14.0? (stale php content)

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]
LGTM

Note that there is an automated task in the Windows release build that deploys help files to /products/desktop which will need updating before this lands in production.

**Comment by darcywong00** [comment]
> Note that there is an automated task in the Windows release build that deploys help files to /products/desktop which will need updating before this lands in production.

Is it this task?
https://github.com/keymanapp/keyman/blob/master/windows/src/buildtools/help-keyman-com.sh

It looks like master and beta already deploy to products/windows

**Comment by mcdurdin** [comment]
> It looks like master and beta already deploy to products/windows

Guess I already did the work on that, and forgot.

**Comment by darcywong00** [comment]
It should be safe to delete products/desktop/14.0, right?

**Comment by mcdurdin** [comment]
yes

**Pull request merged**
