### PR TITLE
change: reworks KMW examples to use init's Promise

### PR DESCRIPTION
**Pull request by jahorton**
Addresses the 'documentation' aspect of https://github.com/keymanapp/keyman/issues/4143.

### CODE REVIEW

**Review by mcdurdin — APPROVED** [review]

**Comment by mcdurdin** [comment]
Note: these changes were made to 13.0. Do we have 14.0 docs yet (or is @darcywong00 working on that)?

**Comment by darcywong00** [comment]
> Do we have 14.0 docs yet?

https://help.keyman-staging.com/developer/engine/web/14.0/ is live

**Comment by mcdurdin** [comment]
So we'll need to patch these changes into the 14.0 staging source. @jahorton or @darcywong00 who wants to do that? 🤣

**Comment by jahorton** [comment]
> So we'll need to patch these changes into the 14.0 staging source. @jahorton or @darcywong00 who wants to do that? 🤣

I can cover it.

**Pull request merged**
