### PR TITLE
Add "Keyman has the wrong name for my language" item to knowledge base

### PR DESCRIPTION
**Pull request by DavidLRowe**
I used the next available number to name the file. Is there anything else to do so the file is included?

### CODE REVIEW

**Comment by mcdurdin** [comment]
> I used the next available number to name the file. Is there anything else to do so the file is included?

That's all that's needed 👍

**Review by mcdurdin — CHANGES_REQUESTED** [review]
The file looks good, but sadly `staging` branch already has a kb0098.md so you'll need to rename this one to kb0099.md.

**Comment by darcywong00** [comment]
Just noting this came out of discussion of https://github.com/keymanapp/keyboards/pull/1340#issuecomment-698667099

**Comment by DavidLRowe** [comment]
@mcdurdin Should be good now.

**Review by mcdurdin — APPROVED** [review]

**Pull request merged**
